# This is a basic workflow

name: CI

#Controls when the action will run.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
 # API_KEY: ${{ secrets.API_KEY }}

  #Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Generate API Key properties file
        run: |
          echo "API_KEY="${{ secrets.API_KEY }}"" > /home/runner/work/MovieApp/MovieApp/apikey.properties
          echo "BASE_URL="${{ secrets.BASE_URL }}"" >> /home/runner/work/MovieApp/MovieApp/apikey.properties
          echo "BASE_URL_IMAGE="${{ secrets.BASE_URL_IMAGE }}"" >> /home/runner/work/MovieApp/MovieApp/apikey.properties
      

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/reports/lint-results-debug.html

        
